# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'bubbles' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bubbles
  pod 'BoringSSL', '~> 9.1'
  pod 'Snappy', '~> 1.1'
  pod 'SolidFrame/frame_mpipc', :configuration => 'Debug', :git => 'https://github.com/vipalade/solidframe.git', :branch => 'podspec'
  pod 'SolidFrame/serialization', :configuration => 'Debug', :git => 'https://github.com/vipalade/solidframe.git', :branch => 'podspec'
  pod 'SolidFrame/frame_aio_openssl', :configuration => 'Debug', :git => 'https://github.com/vipalade/solidframe.git', :branch => 'podspec'
  pod 'BubblesEngine', :configuration => 'Debug', :path => '../../../'
end
