SET(QT_ROOT_DIR ${EXTERN_PATH})

set(QT_QMAKE_EXECUTABLE ${QT_ROOT_DIR}/bin/qmake)

list(APPEND CMAKE_PREFIX_PATH "${EXTERN_PATH}")

find_package(Qt5 REQUIRED COMPONENTS Widgets Core) 

#INCLUDE(${QT_USE_FILE})
ADD_DEFINITIONS(${QT_DEFINITIONS})


